version: '3'

services:
  mariadb:
    image: mariadb:10.3
    container_name: mariadb-stech
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      TZ: 'Asia/Tokyo'
    volumes:
      - ./database/data:/var/lib/mysql  
      - ./database/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./database/initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-stech
    depends_on:
      - mariadb
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS=mariadb
      - PMA_USER=root
      - PMA_PASSWORD=root
    ports:
      - "3000:80"
    volumes:
      - ./docker/phpmyadmin/sessions:/sessions

  api-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-server-stech
    ports:
      - 1323:1323
    tty: true

volumes:
  postgres:
  pgadmin:
