version: '3'


services:
  mariadb:
    image: mariadb:10.3
    container_name: mariadb-stech
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      TZ: 'Asia/Tokyo'
    volumes:
      - ./database/data:/var/lib/mysql  
      - ./database/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./database/initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-stech
    environment:
      # - PMA_ARBITRARY=1
      # - PMA_HOSTS=mariadb
      # - PMA_USER=root
      # - PMA_PASSWORD=root
      # - PMA_PORT=3306
      # - PMA_DATABASE=db
      - PMA_HOSTS=r98du2bxwqkq3shg.cbetxkdyhwsb.us-east-1.rds.amazonaws.com
      - PMA_USER=fcxjqrrnpl2zeqod
      - PMA_PASSWORD=uw925vz81qi2lo28
      - PMA_PORT=3306
      - PMA_DATABASE=u5dgnkfxds9253ou
    depends_on:
      - mariadb
    ports:
      - "3000:80"
    volumes:
      - ./docker/phpmyadmin/sessions:/sessions
