version: '3'

services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-stech
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS=r98du2bxwqkq3shg.cbetxkdyhwsb.us-east-1.rds.amazonaws.com
      - PMA_USER=fcxjqrrnpl2zeqod
      - PMA_PASSWORD=uw925vz81qi2lo28
      - PMA_PORT=3306
      - PMA_DATABASE=u5dgnkfxds9253ou
    ports:
      - "3000:80"
    volumes:
      - ./docker/phpmyadmin/sessions:/sessions

  api-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-server-stech
    environment: 
      - DB_HOST=r98du2bxwqkq3shg.cbetxkdyhwsb.us-east-1.rds.amazonaws.com
      - DB_USER=fcxjqrrnpl2zeqod
      - DB_PASSWORD=uw925vz81qi2lo28
      - DB_PORT=3306
      - DB_NAME=u5dgnkfxds9253ou
    ports:
      - "1323:1323"
    tty: true

volumes:
  postgres:
  pgadmin:
