version: '3'

# services:
#   phpmyadmin:
#     image: phpmyadmin/phpmyadmin
#     container_name: phpmyadmin-stech
#     ports:
#       - "3000:80"
#     volumes:
#       - ./docker/phpmyadmin/sessions:/sessions

  # api-server:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: api-server-stech
  #   ports:
  #     - "1323:1323"
  #   tty: true

volumes:
  postgres:
  pgadmin:
